<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <RootNamespace>$(ModNameSpace).Preloader</RootNamespace>
        <AssemblyName>$(ModName).Preloader</AssemblyName>
        <AssemblyTitle>$(ModName) - Preloader</AssemblyTitle>
        <Product>$(ModName)</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="5.4.21"/>

    </ItemGroup>

    <!-- Defining the reference files that have to be publicized. -->
    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all"/>

        <!-- Publicize directly when referencing -->

        <!-- clean referencing -->
    </ItemGroup>

    <!--Publishing steps-->
    <Target Name="CopyForUpload" AfterTargets="Build">
        <PropertyGroup>
            <DistributionDir>$(SolutionDir)\Output\dist</DistributionDir>
        </PropertyGroup>
        <PropertyGroup>
            <PreloaderOutDir>$(SolutionDir)\Preloader\$(OutDir)</PreloaderOutDir>
            <PreloaderDistributionDir>$(DistributionDir)\BepInEx\patchers</PreloaderDistributionDir>
        </PropertyGroup>

        <Message Importance="High" Text="Copyng Preloader to DistributionDir" />

        <MakeDir Directories="$(PreloaderDistributionDir)"/>
        <ItemGroup>
            <PreloaderOutputFiles Include="$(PreloaderOutDir)\**" Exclude="$(PreloaderOutDir)\**\*.deps.json" />
        </ItemGroup>
        <Copy
                SourceFiles="@(PreloaderOutputFiles)"
                DestinationFolder="$(PreloaderDistributionDir)"
        />
    </Target>
</Project>
